name: Build/Release Cross-Platform

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: './desktop/package-lock.json'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies & Build Frontend
        run: |
          cd frontend
          npm install
          npm run build
          cd ..

      - name: Install Desktop Dependencies
        run: |
          cd desktop
          npm install
          cd ..

      - name: Build/Release Electron App
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          package_root: 'desktop'
          # Supprimé --config car package_root déplace déjà le contexte dans ./desktop
          args: ""
          release: true
